/**
 * Writes the served OpenAPI document to a file.
 *
 * The document is requested from the running application in process rather
 * than regenerated by a second code path, so the exported file cannot drift
 * from what `/openapi.json` actually serves.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { createApp, type App } from "../src/app.js";
import { fixtureRepository } from "../src/data/fixtures.js";

export const DEFAULT_OUTPUT_PATH = "dist/openapi.json";

/**
 * Requests `/openapi.json` and writes it to `outputPath`.
 *
 * @param app - Supplied by the tests to exercise the failure paths; defaults
 *   to the same application `src/index.ts` starts.
 * @returns The absolute path that was written.
 * @throws If the endpoint does not answer 2xx, or answers with something that
 *   is not JSON. A truncated or error-shaped spec must never be written.
 */
export async function exportOpenApi(
  outputPath: string = DEFAULT_OUTPUT_PATH,
  app: App = createApp({ repository: fixtureRepository })
): Promise<string> {
  const response = await app.request("/openapi.json");

  if (!response.ok) {
    throw new Error(`GET /openapi.json responded with ${response.status}`);
  }

  const body = await response.text();
  let document: unknown;
  try {
    document = JSON.parse(body);
  } catch (cause) {
    throw new Error("GET /openapi.json did not return readable JSON", { cause });
  }

  const absolute = resolve(outputPath);
  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, `${JSON.stringify(document, null, 2)}\n`, "utf8");
  return absolute;
}

const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  const written = await exportOpenApi(process.argv[2] ?? DEFAULT_OUTPUT_PATH);
  console.log(`Wrote ${written}`);
}
